from snakemake.utils import min_version

# Minimum snakemake version
min_version("5.10.0")


# Pipeline settings
configfile: "config/config.yaml"


# Rules


rule all:
    input:
        # "data/1/paired-end/sample1.fastq.gz",
        # "data/1/paired-end/sample2.fastq.gz",
        # "preprocessed_reads/1/paired-end/sample1.fastq.gz",
        # "preprocessed_reads/1/paired-end/sample2.fastq.gz",
        directory("assembly/final.contigs.fa"),


# Load rules


include: "rules/QualityControl.smk"
include: "rules/Assembly.smk"
